/**
 * Sync Document to Zoho
 *
 * Delegates invoice/credit-note creation to Zoho Books/Invoice via the POP API's
 * native Zoho connector. All Zoho-side mapping (tax, customer, payment terms,
 * document status) is handled server-side in pop-cloud-api — this operation only
 * gates the request on the connector being active, then forwards the POP payload.
 *
 * Flow:
 * 1. (optional) GET integration/zoho/status — verify the Zoho connector is active
 *    for this account before attempting to sync
 * 2. POST integration/zoho/sync — forward the POP payload; the backend maps it
 *    to a Zoho invoice (TD01) or credit note (TD04)
 *
 * Supports passthrough, form, and JSON input modes (no raw — the endpoint only
 * accepts JSON).
 *
 * POP API endpoints: GET /integration/zoho/status, POST /integration/zoho/sync
 */
import type { IExecuteFunctions, INodePropertyOptions } from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';
import { InvoicesProperties } from '../types/pop';
import { popRequest, type PopRequestOptions } from '../utils/request';
import { makeInvoiceFormFields } from './invoiceFields';
import { buildInvoicePayload, type InvoiceFormParams } from './invoicePayloadBuilder';

/** Operation metadata shown in the n8n operation selector dropdown */
export const options: INodePropertyOptions = {
	name: 'Sync Document to Zoho',
	value: 'syncZohoDocument',
	description:
		'Sync an invoice or credit note to Zoho Books/Invoice via the POP API Zoho connector',
	action: 'Sync document to Zoho',
};

const OPERATION = 'syncZohoDocument';

/**
 * Node properties (UI fields) for this operation.
 * Displayed when the user selects resource=invoices and operation=syncZohoDocument.
 */
export const properties: InvoicesProperties = [
	{
		displayName: 'Environment',
		name: 'baseUrl',
		type: 'options',
		options: [
			// { name: 'Staging', value: 'staging' },
			{ name: 'Production', value: 'production' },
		],
		default: 'production',
		displayOptions: { show: { resource: ['invoices'], operation: [OPERATION] } },
		description: 'The POP API environment to use',
	},
	// Status-gate toggle — verifies the Zoho connector is active before syncing
	{
		displayName: 'Check Connector Status First',
		name: 'checkConnectorStatus',
		type: 'options',
		options: [
			{ name: 'Yes', value: 'yes' },
			{ name: 'No', value: 'no' },
		],
		default: 'yes',
		displayOptions: { show: { resource: ['invoices'], operation: [OPERATION] } },
		description:
			'Whether to verify that the Zoho connector is active for this account before attempting the sync. If not active, the operation fails with a clear error instead of a Zoho-side rejection.',
	},
	// Configurable status-check path
	{
		displayName: 'Status Path',
		name: 'statusPath',
		type: 'string',
		default: 'integration/zoho/status',
		displayOptions: { show: { resource: ['invoices'], operation: [OPERATION] } },
		description: 'Relative path of the POP connector status endpoint',
	},
	// Configurable sync endpoint path
	{
		displayName: 'Endpoint Path',
		name: 'path',
		type: 'string',
		default: 'integration/zoho/sync',
		displayOptions: { show: { resource: ['invoices'], operation: [OPERATION] } },
		description: 'Relative path of the POP Zoho sync endpoint. Adjust if your API uses a different route.',
	},
	// Input mode selector — determines how the request body is built
	{
		displayName: 'Input Mode',
		name: 'inputMode',
		type: 'options',
		noDataExpression: true,
		options: [
			{ name: 'Use Incoming JSON', value: 'passthrough' },
			{ name: 'Form Fields', value: 'form' },
			{ name: 'JSON', value: 'json' },
		],
		default: 'passthrough',
		displayOptions: { show: { resource: ['invoices'], operation: [OPERATION] } },
		description:
			'Use Incoming JSON forwards the input item as-is (ideal for webhooks). Form Fields lets you fill in each field. JSON allows a manual payload.',
	},
	// ── Form fields (visible when inputMode = form) ──
	// Generated by the shared factory; Zoho reuses the SdI/Peppol-neutral subset
	...makeInvoiceFormFields(OPERATION),
	// ── JSON body (visible when inputMode = json) ──
	{
		displayName: 'JSON Body',
		name: 'jsonBody',
		type: 'json',
		default:
			'{\n  "license_key": "your_license_key",\n  "data": {\n    "id": 0,\n    "filename": "",\n    "type": "invoice",\n    "customer_type": "private",\n    "transferee_client": {},\n    "invoice_body": {\n      "general_data": {\n        "doc_type": "TD01",\n        "date": "",\n        "currency": "EUR"\n      }\n    },\n    "order_items": []\n  }\n}',
		displayOptions: {
			show: { resource: ['invoices'], operation: [OPERATION], inputMode: ['json'] },
		},
		description: 'Complete request body as JSON. Must follow the POP API v2 integration/zoho/sync schema. For TD04 (Credit Note), the first entry of connected_invoice_data must include a numeric identifier.',
	},
	// Extra headers — merged with the default headers for all input modes
	{
		displayName: 'Extra Headers (JSON)',
		name: 'headers',
		type: 'json',
		default: '{}',
		displayOptions: { show: { resource: ['invoices'], operation: [OPERATION] } },
		description: 'Optional additional headers as a JSON object. Example: setting a custom Content-Type header.',
	},
];

/**
 * Operation handler — verifies the Zoho connector status (optional), then
 * builds and sends the integration/zoho/sync request.
 *
 * Depending on the selected input mode:
 * - passthrough: forwards the incoming n8n item JSON directly
 * - form: assembles the payload using buildInvoicePayload() with variant='zoho'
 * - json: uses the user-provided JSON body as-is
 *
 * The response distinguishes the status-check outcome from the sync outcome
 * so downstream nodes can branch on either without losing the raw POP response.
 */
export async function handler(
	this: IExecuteFunctions,
	params: {
		baseUrl?: string;
		path: string;
		statusPath: string;
		checkConnectorStatus: 'yes' | 'no';
		inputMode: 'form' | 'json' | 'passthrough';
		jsonBody?: object;
		headers?: Record<string, string>;
		_itemIndex?: number;
	} & Partial<InvoiceFormParams>,
): Promise<unknown> {
	const { baseUrl, path, statusPath, checkConnectorStatus, inputMode, headers } = params;
	const itemIndex = params._itemIndex ?? 0;

	const sharedHeaders: Record<string, string> = { ...(headers ?? {}) };
	const formKey = (params.licenseKey ?? '').trim();
	if (formKey) {
		sharedHeaders['X-API-Key'] = formKey;
	}

	let connectorActive: boolean | null = null;
	let statusChecked = false;

	if (checkConnectorStatus === 'yes') {
		statusChecked = true;
		const statusResponse = (await popRequest.call(
			this,
			{ url: statusPath, method: 'GET', headers: { ...sharedHeaders } },
			baseUrl,
		)) as { data?: { active_connector?: string; zoho_connected?: boolean } };

		connectorActive =
			statusResponse?.data?.active_connector === 'zoho' && statusResponse?.data?.zoho_connected === true;

		if (!connectorActive) {
			throw new NodeOperationError(
				this.getNode(),
				'Zoho integration is not active for this account. Enable it from the POP account panel before using this action.',
				{ itemIndex },
			);
		}
	}

	const requestOptions: PopRequestOptions = {
		url: path,
		method: 'POST',
		headers: { ...sharedHeaders },
	};

	if (inputMode === 'passthrough') {
		// Forward the incoming item's JSON data directly to the API
		requestOptions.json = true;
		requestOptions.body = { ...this.getInputData()[itemIndex].json };
	} else if (inputMode === 'form') {
		// Build the structured payload from form field values using the Zoho variant.
		// sendInvoice is always false — Zoho sync has no integration.use/action toggle.
		requestOptions.json = true;
		requestOptions.body = buildInvoicePayload(params as InvoiceFormParams, 'zoho', false);
	} else {
		// Use the manually provided JSON body
		requestOptions.json = true;
		requestOptions.body = (params.jsonBody ?? {}) as Record<string, unknown>;
	}

	const syncResponse = await popRequest.call(this, requestOptions, baseUrl);

	return {
		connector_active: connectorActive,
		status_checked: statusChecked,
		sync_attempted: true,
		response: syncResponse,
	};
}
